// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class ExampleServiceBindings
    {
        readonly ICloudCodeService k_Service;

        public ExampleServiceBindings() : this(CloudCodeService.Instance) { }

        public ExampleServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SetExampleData()
        {
            await k_Service.CallModuleEndpointAsync(
                "Project",
                "SetExampleData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<List<string>> GetExampleData()
        {
            return await k_Service.CallModuleEndpointAsync<List<string>>(
                "Project",
                "GetExampleData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> CreateCard()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Project",
                "CreateCard",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> StoreGameState()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Project",
                "StoreGameState",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<Game.Domain.Models.Card> DrawCard()
        {
            return await k_Service.CallModuleEndpointAsync<Game.Domain.Models.Card>(
                "Project",
                "DrawCard",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<int> Get0()
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "Project",
                "Get0",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
