// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Domain.Models.Dto
{
    public partial class CardResult
    {
        public bool HasCard;
        public Card Card;

        [Preserve]
        public CardResult ()
        {
        }
    }
}