// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Domain.Models.Dto
{
    public partial class Match
    {
        public string MatchId;
        public ClientGameState ClientGameState;

        [Preserve]
        public Match ()
        {
        }
    }
}