// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GameLogicServiceBindings
    {
        readonly ICloudCodeService k_Service;

        public GameLogicServiceBindings() : this(CloudCodeService.Instance) { }

        public GameLogicServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Game.Domain.Models.Dto.Match> CreateMatch()
        {
            return await k_Service.CallModuleEndpointAsync<Game.Domain.Models.Dto.Match>(
                "Project",
                "CreateMatch",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<Game.Domain.Models.Dto.MoveRequestResult> Request(Game.Domain.Models.Move move, string matchId)
        {
            return await k_Service.CallModuleEndpointAsync<Game.Domain.Models.Dto.MoveRequestResult>(
                "Project",
                "Request",
                new Dictionary<string, object>()
                {
                    {"move", move},
                    {"matchId", matchId},
                });
        }

        public async Task<Game.Domain.Models.ClientGameState> GetClientGameState(string matchId, Game.Domain.Models.Team team)
        {
            return await k_Service.CallModuleEndpointAsync<Game.Domain.Models.ClientGameState>(
                "Project",
                "GetClientGameState",
                new Dictionary<string, object>()
                {
                    {"matchId", matchId},
                    {"team", team},
                });
        }

        public async Task<bool> DeleteMatch(string matchId)
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "Project",
                "DeleteMatch",
                new Dictionary<string, object>()
                {
                    {"matchId", matchId},
                });
        }
    }
}
