// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PushMessagesServiceBindings
    {
        readonly ICloudCodeService k_Service;

        public PushMessagesServiceBindings() : this(CloudCodeService.Instance) { }

        public PushMessagesServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<bool> ChallengeFriend(string challengerName, string challengedPlayerId)
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "Project",
                "ChallengeFriend",
                new Dictionary<string, object>()
                {
                    {"challengerName", challengerName},
                    {"challengedPlayerId", challengedPlayerId},
                });
        }
    }
}
