// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Domain.Models.Dto
{
    public partial class MoveRequestResult
    {
        public bool HasCard;
        public bool IsOutOfSync;
        public Card Card;
        public int DeltaScore;

        [Preserve]
        public MoveRequestResult ()
        {
        }
    }
}