<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release</Configurations>
    <EnableSourceControlManagerQueries>false</EnableSourceControlManagerQueries>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Com.Unity.Services.CloudCode.Apis" Version="0.0.26" />
    <PackageReference Include="Com.Unity.Services.CloudCode.Core" Version="0.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\Assets\Scripts\Game\Domain\**\*.cs" Link="Domain\%(RecursiveDir)%(FileName)%(Extension)" />
    <Compile Include="..\..\Library\PackageCache\com.*.utilitytoolkit*\**\*.cs"
             Exclude="..\..\Library\PackageCache\com.*.utilitytoolkit*\**\*Editor*\**\*.cs;
                    ..\..\Library\PackageCache\com.*.utilitytoolkit*\**\*Test*\**\*.cs;"
             Link="UtilityToolkit\%(RecursiveDir)%(FileName)%(Extension)" />
  </ItemGroup>
  <PropertyGroup>
    <PublishReadyToRunComposite>true</PublishReadyToRunComposite>
  </PropertyGroup>
  <!--    <Target Name="Zip" AfterTargets="Publish">-->
  <!--        <Message Importance="high" Text="Zipping output!!"/>-->
  <!--        <Exec Command="zip -r $(SolutionDir)ExampleModule.ccm $(PublishDir)" />-->
  <!--    </Target>-->
</Project>