// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class ExampleServiceBindings
    {
        readonly ICloudCodeService k_Service;

        public ExampleServiceBindings() : this(CloudCodeService.Instance) { }

        public ExampleServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SetExampleData()
        {
            await k_Service.CallModuleEndpointAsync(
                "Cloud_Code_Module_Reference",
                "SetExampleData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<List<string>> GetExampleData()
        {
            return await k_Service.CallModuleEndpointAsync<List<string>>(
                "Cloud_Code_Module_Reference",
                "GetExampleData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<Game.Domain.Models.Position> SendPosition(Game.Domain.Models.Position position)
        {
            return await k_Service.CallModuleEndpointAsync<Game.Domain.Models.Position>(
                "Cloud_Code_Module_Reference",
                "SendPosition",
                new Dictionary<string, object>()
                {
                    {"position", position},
                });
        }

        public async Task<Game.Domain.Models.Card> SendCard(Game.Domain.Models.Card card)
        {
            return await k_Service.CallModuleEndpointAsync<Game.Domain.Models.Card>(
                "Cloud_Code_Module_Reference",
                "SendCard",
                new Dictionary<string, object>()
                {
                    {"card", card},
                });
        }

        public async Task SendMove(Game.Domain.Models.Move move)
        {
            await k_Service.CallModuleEndpointAsync(
                "Cloud_Code_Module_Reference",
                "SendMove",
                new Dictionary<string, object>()
                {
                    {"move", move},
                });
        }

        public async Task SendGameStateData(Game.Domain.Models.GameStateData gameState)
        {
            await k_Service.CallModuleEndpointAsync(
                "Cloud_Code_Module_Reference",
                "SendGameStateData",
                new Dictionary<string, object>()
                {
                    {"gameState", gameState},
                });
        }

        public async Task GetGameState(Game.Domain.Models.GameStateData gameState)
        {
            await k_Service.CallModuleEndpointAsync(
                "Cloud_Code_Module_Reference",
                "GetGameState",
                new Dictionary<string, object>()
                {
                    {"gameState", gameState},
                });
        }
    }
}
