// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class ExampleServiceBindings
    {
        readonly ICloudCodeService k_Service;

        public ExampleServiceBindings() : this(CloudCodeService.Instance) { }

        public ExampleServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SetExampleData()
        {
            await k_Service.CallModuleEndpointAsync(
                "Cloud_Code_Module_Reference",
                "SetExampleData",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
