// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Domain.Models
{
    public partial class Hand
    {
        public int Count;
        public bool IsFull;

        [Preserve]
        public Hand ()
        {
        }
    }
}