// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Domain.Models
{
    public enum Team
    {
        Red = 0,
        Yellow = 1,
    }
}
