// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Domain.Models
{
    public partial class Position
    {
        public Row Row;
        public Column Column;

        [Preserve]
        public Position ()
        {
        }
    }
}