// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Models
{
    public enum Row
    {
        One = 0,
        Two = 1,
        Three = 2,
        Four = 3,
        Five = 4,
        Six = 5,
    }
}
