// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Models
{
    public partial class Card
    {
        public Rank Rank;
        public Symbol Symbol;
        public bool IsWild;
        public bool IsRemover;

        [Preserve]
        public Card ()
        {
        }
    }
}