// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Domain.Models
{
    public partial class GameState
    {
        public Hand RedHand;
        public Hand YellowHand;
        public Deck Deck;
        public Board Board;
        public MoveHistory MoveHistory;
        public Team ToPlay;

        [Preserve]
        public GameState ()
        {
        }
    }
}