// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Models
{
    public enum Symbol
    {
        Sun = 0,
        Moon = 1,
    }
}
