// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Domain.Models
{
    public partial class GameStateData
    {
        public List<Move> Moves;
        public List<Card> Deck;
        public List<Card> RedHand;
        public List<Card> YellowHand;

        [Preserve]
        public GameStateData ()
        {
        }
    }
}