// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Game.Domain.Models
{
    public partial class ClientGameState
    {
        public List<Move> Moves;
        public List<Card> Hand;
        public Team Team;
        public Score Score;
        public bool IsMyTurn;

        [Preserve]
        public ClientGameState ()
        {
        }
    }
}