// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GameLogicServiceBindings
    {
        readonly ICloudCodeService k_Service;

        public GameLogicServiceBindings() : this(CloudCodeService.Instance) { }

        public GameLogicServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Game.Domain.Models.Dto.CardResultDto> Request(Game.Domain.Models.Move move)
        {
            return await k_Service.CallModuleEndpointAsync<Game.Domain.Models.Dto.CardResultDto>(
                "Cloud_Code_Module_Reference",
                "Request",
                new Dictionary<string, object>()
                {
                    {"move", move},
                });
        }
    }
}
