// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class MultiplayerServiceBindings
    {
        readonly ICloudCodeService k_Service;

        public MultiplayerServiceBindings() : this(CloudCodeService.Instance) { }

        public MultiplayerServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Game.Models.Players.GameStateData> GetGameStateData()
        {
            return await k_Service.CallModuleEndpointAsync<Game.Models.Players.GameStateData>(
                "Cloud_Code_Module_Reference",
                "GetGameStateData",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
