// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.

namespace Unity.Services.CloudCode.GeneratedBindings.Unity.Services.CloudCode.GeneratedBindings.Game.Models
{
    public enum Rank
    {
        Ace = 0,
        Two = 1,
        Three = 2,
        Four = 3,
        Five = 4,
        Six = 5,
        Seven = 6,
        Eight = 7,
        Nine = 8,
        Ten = 9,
        Jack = 10,
        Queen = 11,
        King = 12,
    }
}
