// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Unity.Services.CloudCode.GeneratedBindings.Game.Models.Players
{
    public partial class Move
    {
        public Position Position;
        public Card Card;
        public Team Team;

        [Preserve]
        public Move ()
        {
        }
    }
}